### ISSUE TITLE
Ability to reply to the message via email

### ISSUE THREAD

**Issue by goshakkk** [evrone/inboxes#7]
I've seen this feature here on Github. If I get direct message or a new message in the issue discussion, I can just reply to email (which is sent from a special address, like `reply+i-LONGTOKENGOESHERE@site.com`) instead of going to my inbox and manually replaying.

It's super useful, especially when there is only my iPhone next to me at the moment.

What do you think about implementing it and then having an option on Inboxes initializer to enable such a cool feature?

**Comment by smalew** [comment]
Hello.
Sorry, but this project is archived.
Works by project no longer conducted.
